### ISSUE TITLE
Online tool to create content loaders for Vue not working

### ISSUE THREAD

**Issue by pranavjindal999** [egoist/vue-content-loader#16]
Hey. Thanks for the awesome project.

Vue content loader online tool isn't working anymore.

http://danilowoz.com/create-content-loader/
There is no vue creater (it was there few days back)

![image](https://user-images.githubusercontent.com/5094327/47072525-d97f2480-d213-11e8-806a-88612efa4ba3.png)

**Comment by pranavjindal999** [comment]
I looked for the issue, and Vue support has been purposely removed

Not sure why :(

https://github.com/danilowoz/create-content-loader/commit/cd287e3208b038e9694fe3cd4224e9b1c84751ea

**Comment by egoist** [comment]
I deployed an older version of create-content-loader: https://create-vue-content-loader.netlify.com/ workaround for now.

**Comment by danilowoz** [comment]
hey @egoist and @pranavjindal999 

Unfortunately, I removed the Vue support to the creator in the last release for some reasons:
- The `react-content-loader` has some new features that `vue-content-loader` doesn't support yet (RTL is an example), therefore I have no control with versions and features for both;
- My ideas about future features to `create-content-loader` are going against to support two libraries at the same place (the gallery is a great example);
- Too much code to support them both and some bugs that required much more code;

But ok, I'm very sad to remove that and I was wondering an alternative to this situation:
- Fork the current version (it needs to be the latest because there are fixed a few bugs) and use the Vue support;
- Create a link to each other;

For now, the link that @egoist created is enough, but I recomend to change the React link to main creator and I can put the Vue icon again appointing to the link above.

What do you think?

**Comment by danilowoz** [comment]
Great news! 🎉 
Vue content loader is up: http://danilowoz.com/create-vue-content-loader/

**Comment by pranavjindal999** [comment]
Thanks @danilowoz
